/*
 * Academic Graph API
 *
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthorInfo1 {
    #[serde(rename = "authorId")]
    pub author_id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl AuthorInfo1 {
    pub fn new(author_id: String, name: String) -> AuthorInfo1 {
        AuthorInfo1 {
            author_id,
            name,
        }
    }
}


