/*
 * Academic Graph API
 *
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthorInfo {
    #[serde(rename = "authorId")]
    pub author_id: String,
    /// ORCID/DBLP IDs for this author, if known
    #[serde(rename = "externalIds", skip_serializing_if = "Option::is_none")]
    pub external_ids: Option<serde_json::Value>,
    /// URL on the Semantic Scholar website
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// List of aliases
    #[serde(rename = "aliases", skip_serializing_if = "Option::is_none")]
    pub aliases: Option<serde_json::Value>,
    /// List of affiliations
    #[serde(rename = "affiliations", skip_serializing_if = "Option::is_none")]
    pub affiliations: Option<serde_json::Value>,
    /// Author's own homepage
    #[serde(rename = "homepage", skip_serializing_if = "Option::is_none")]
    pub homepage: Option<String>,
    /// Author's total publications count
    #[serde(rename = "paperCount", skip_serializing_if = "Option::is_none")]
    pub paper_count: Option<String>,
    /// Author's total citations count
    #[serde(rename = "citationCount", skip_serializing_if = "Option::is_none")]
    pub citation_count: Option<String>,
    /// https://www.semanticscholar.org/faq#h-index
    #[serde(rename = "hIndex", skip_serializing_if = "Option::is_none")]
    pub h_index: Option<String>,
}

impl AuthorInfo {
    pub fn new(author_id: String) -> AuthorInfo {
        AuthorInfo {
            author_id,
            external_ids: None,
            url: None,
            name: None,
            aliases: None,
            affiliations: None,
            homepage: None,
            paper_count: None,
            citation_count: None,
            h_index: None,
        }
    }
}


