/*
 * Academic Graph API
 *
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Embedding {
    /// The underlying model+version that produced the embedding
    #[serde(rename = "model")]
    pub model: String,
    /// Numerical embedding vector
    #[serde(rename = "vector")]
    pub vector: serde_json::Value,
}

impl Embedding {
    pub fn new(model: String, vector: serde_json::Value) -> Embedding {
        Embedding {
            model,
            vector,
        }
    }
}


