/*
 * Academic Graph API
 *
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Error400 {
    /// Depending on the case, error message may be any of these: <ul>     <li><code>\"Unrecognized or unsupported fields: [bad1, bad2, etc...]\"</code></li>     <li><code>\"Unacceptable query params: [badK1=badV1, badK2=badV2, etc...}]\"</code></li>     <li>A custom message string</li></ul>
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl Error400 {
    pub fn new() -> Error400 {
        Error400 {
            error: None,
        }
    }
}


