/*
 * Academic Graph API
 *
 * Fetch paper and author data from the Semantic Scholar Academic Graph (S2AG)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Tldr {
    /// The underlying model+version that produced the tldr
    #[serde(rename = "model")]
    pub model: String,
    /// paper TLDR summary
    #[serde(rename = "text")]
    pub text: String,
}

impl Tldr {
    pub fn new(model: String, text: String) -> Tldr {
        Tldr {
            model,
            text,
        }
    }
}


